// Generated by gencpp from file task4/remove_runnerRequest.msg
// DO NOT EDIT!


#ifndef TASK4_MESSAGE_REMOVE_RUNNERREQUEST_H
#define TASK4_MESSAGE_REMOVE_RUNNERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task4
{
template <class ContainerAllocator>
struct remove_runnerRequest_
{
  typedef remove_runnerRequest_<ContainerAllocator> Type;

  remove_runnerRequest_()
    : runner_id(0)  {
    }
  remove_runnerRequest_(const ContainerAllocator& _alloc)
    : runner_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _runner_id_type;
  _runner_id_type runner_id;





  typedef boost::shared_ptr< ::task4::remove_runnerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task4::remove_runnerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct remove_runnerRequest_

typedef ::task4::remove_runnerRequest_<std::allocator<void> > remove_runnerRequest;

typedef boost::shared_ptr< ::task4::remove_runnerRequest > remove_runnerRequestPtr;
typedef boost::shared_ptr< ::task4::remove_runnerRequest const> remove_runnerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task4::remove_runnerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task4::remove_runnerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace task4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::task4::remove_runnerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task4::remove_runnerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task4::remove_runnerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task4::remove_runnerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task4::remove_runnerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task4::remove_runnerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task4::remove_runnerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36607c52d2756433ed6fc5f2dd2d46f5";
  }

  static const char* value(const ::task4::remove_runnerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36607c52d2756433ULL;
  static const uint64_t static_value2 = 0xed6fc5f2dd2d46f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::task4::remove_runnerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task4/remove_runnerRequest";
  }

  static const char* value(const ::task4::remove_runnerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task4::remove_runnerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 runner_id\n\
";
  }

  static const char* value(const ::task4::remove_runnerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task4::remove_runnerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.runner_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct remove_runnerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task4::remove_runnerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task4::remove_runnerRequest_<ContainerAllocator>& v)
  {
    s << indent << "runner_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.runner_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK4_MESSAGE_REMOVE_RUNNERREQUEST_H
