// Generated by gencpp from file task4/remove_runner.msg
// DO NOT EDIT!


#ifndef TASK4_MESSAGE_REMOVE_RUNNER_H
#define TASK4_MESSAGE_REMOVE_RUNNER_H

#include <ros/service_traits.h>


#include <task4/remove_runnerRequest.h>
#include <task4/remove_runnerResponse.h>


namespace task4
{

struct remove_runner
{

typedef remove_runnerRequest Request;
typedef remove_runnerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct remove_runner
} // namespace task4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task4::remove_runner > {
  static const char* value()
  {
    return "5f1cf5e22cd9743828e3c4016d34e92c";
  }

  static const char* value(const ::task4::remove_runner&) { return value(); }
};

template<>
struct DataType< ::task4::remove_runner > {
  static const char* value()
  {
    return "task4/remove_runner";
  }

  static const char* value(const ::task4::remove_runner&) { return value(); }
};


// service_traits::MD5Sum< ::task4::remove_runnerRequest> should match 
// service_traits::MD5Sum< ::task4::remove_runner > 
template<>
struct MD5Sum< ::task4::remove_runnerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task4::remove_runner >::value();
  }
  static const char* value(const ::task4::remove_runnerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task4::remove_runnerRequest> should match 
// service_traits::DataType< ::task4::remove_runner > 
template<>
struct DataType< ::task4::remove_runnerRequest>
{
  static const char* value()
  {
    return DataType< ::task4::remove_runner >::value();
  }
  static const char* value(const ::task4::remove_runnerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task4::remove_runnerResponse> should match 
// service_traits::MD5Sum< ::task4::remove_runner > 
template<>
struct MD5Sum< ::task4::remove_runnerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task4::remove_runner >::value();
  }
  static const char* value(const ::task4::remove_runnerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task4::remove_runnerResponse> should match 
// service_traits::DataType< ::task4::remove_runner > 
template<>
struct DataType< ::task4::remove_runnerResponse>
{
  static const char* value()
  {
    return DataType< ::task4::remove_runner >::value();
  }
  static const char* value(const ::task4::remove_runnerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK4_MESSAGE_REMOVE_RUNNER_H
